// update
export const UPDATE_ROSTER = "UPDATE_ROSTER"
export const UPDATE_WRESTLER = "UPDATE_WRESTLER"
export const UPDATE_SHOWS = "UPDATE_SHOWS"
export const UPDATE_CHAMPIONS = "UPDATE_CHAMPIONS"
export const UPDATE_STYLE = "UPDATE_STYLE"

// brand
export const CREATE_BRAND = "CREATE_BRAND"
export const UPDATE_BRAND = "UPDATE_BRAND"
export const DELETE_BRAND = "DELETE_BRAND"

// game
export const START_GAME = "START_GAME"
export const GENERATE_FEDERATION = "GENERATE_FEDERATION"
export const GENERATE_SHOWS = "GENERATE_SHOWS"
export const GENERATE_CHAMPIONSHIPS = "GENERATE_CHAMPIONSHIPS"
export const TOGGLE_ANIMATIONS = "TOGGLE_ANIMATIONS"
export const CHECK_VERSION = "CHECK_VERSION"

// roster
export const GENERATE_ROSTER = "GENERATE_ROSTER"
export const CREATE_WRESTLER = "CREATE_WRESTLER"

// matches
export const CREATE_MATCH = "CREATE_MATCH"
export const SIMULATE_RANDOM_MATCH = "SIMULATE_RANDOM_MATCH"
export const SELECT_WINNER_IN_MATCH = "SELECT_WINNER_IN_MATCH"
export const RANDOMISE_SHOW = "RANDOMISE_SHOW"
export const SIMULATE_SHOW = "SIMULATE_SHOW"
export const REMOVE_WRESTLER_FROM_MATCH = "REMOVE_WRESTLER_FROM_MATCH"
export const REMOVE_WRESTLER = "REMOVE_WRESTLER"
export const ADD_WRESTLER_TO_MATCH = "ADD_WRESTLER_TO_MATCH"
export const SIMULATE_MATCH = "SIMULATE_MATCH"
export const GENERATE_RANDOM_MATCHES = "GENERATE_RANDOM_MATCHES"
export const SIMULATE_GENERATED_RANDOM_MATCHES = "SIMULATE_GENERATED_RANDOM_MATCHES"

// accounting
export const UPDATE_GAME = "UPDATE_GAME"
export const ADD_PROFIT = "ADD_PROFIT"

// resets
export const RESET = "RESET"
export const RESET_GAME = "RESET_GAME"
export const RESET_MATCHES = "RESET_MATCHES"
export const RESET_MATCH = "RESET_MATCH"
export const RESET_NOTIFICATIONS = "RESET_NOTIFICATIONS"
export const RESET_BRANDS = "RESET_BRANDS"

// removals
export const REMOVE_NOTIFICATION = "REMOVE_NOTIFICATION"

// sizes
export const lg = "lg"
export const md = "md"
export const sm = "sm"
export const xs = "xs"

// droppables
export const WRESTLER = "WRESTLER"
