export const SEARCH = "SEARCH"

export const SHOULD_MOVE_CHAMPIONSHIP = "SHOULD_MOVE_CHAMPIONSHIP"
export const MOVE_CHAMPIONSHIP = "MOVE_CHAMPIONSHIP"
export const CLEAR_SELECTED_CHAMPIONS = "CLEAR_SELECTED_CHAMPIONS"
export const RESET_CHAMPIONS = "RESET_CHAMPIONS"
export const CLEAR_CHAMPIONS = "CLEAR_CHAMPIONS"

export const MOVE_All_WRESTLERS_TO_DEFAULT = "MOVE_All_WRESTLERS_TO_DEFAULT"
export const MOVE_WRESTLER = "MOVE_WRESTLER"
export const AWARD_MATCH_POINTS = "AWARD_MATCH_POINTS"
export const RESET_WRESTLERS = "RESET_WRESTLERS"
export const CLEAR_WRESTLERS = "CLEAR_WRESTLERS"
