export const CHAMPIONSHIP_RESET_CONFIRM = "Are you sure you want to reset all champions and generate random replacements?"
export const MATCH_CONFIRM_RESET = "Are you sure you want to clear your match history?"
export const ROSTER_CONFIRM_RESET = "Are you sure you want to reset all wrestlers and generate random replacements?"
export const WRESTLER_CONFIRM_DELETE = "Are you sure you want to delete this wrestler?"
export const BRAND_CONFIRM_DELETE = "Are you sure you want to delete this brand?"
export const BRANDS_CONFIRM_CLEAR = "Are you sure you want to clear your brands?"
export const ADD_BRAND_ENTRY = "Type a brand name and hit enter"
